### PR TITLE
Update pytest-cov to 2.4.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by dopplershift** [comment]
Can you [re-render](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) the feedstock with conda-smithy 1.3.3 and push those changes to your master branch? That should fix the build problems.

**Comment by nicoddemus** [comment]
Just did it! 😄

**Comment by dopplershift** [comment]
Well that's a weird message. @conda-forge/core any ideas?

**Comment by nicoddemus** [comment]
Yeah, the `checkout_merge_commit.sh` script seems to be in place... strange.

**Comment by jakirkham** [comment]
That's an odd one. Going to restart and hope it was some transient CircleCI problem.

**Comment by jakirkham** [comment]
Weird. Could you please try doing `chmod +x` on that script and committing?

**Comment by nicoddemus** [comment]
No change for me:

```
vagrant@thdengops-ubuntu-14:/vagrant/pytest-cov-feedstock$ chmod a+x ci_support/checkout_merge_commit.sh
vagrant@thdengops-ubuntu-14:/vagrant/pytest-cov-feedstock$ git st
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

I wonder if the reason is that I'm on a vagrant box?

**Comment by nicoddemus** [comment]
Goddamit, I think that's it, I cloned the recipe on a shared folder with Windows!

**Comment by jakirkham** [comment]
Was wondering if Windows was in play. Do you mind filing an issue over at [conda-smithy]( https://github.com/conda-forge/conda-smithy )? We have been relying on executable permissions, which are not a sensible thing for us to rely on with Windows. We should start prefixing things like this with `bash` which should be an easy fix. Sorry for the hassle.

**Comment by jakirkham** [comment]
Should add I pushed the permission fixed file to your branch and it seems to be behaving correctly now FWICT.

**Comment by nicoddemus** [comment]
> Should add I pushed the permission fixed file to your branch and it seems to be behaving correctly now FWICT.

Perfect, many thanks! I reported conda-forge/conda-smithy#330 as you asked. 😁

**Comment by jakirkham** [comment]
Awesome. Thanks.

**Comment by dopplershift** [comment]
Thanks! @nicoddemus if you're doing a lot of stuff in the pytest space, feel free to submit a PR adding yourself as a maintainer in the recipe here.

**Comment by nicoddemus** [comment]
>  if you're doing a lot of stuff in the pytest space, feel free to submit a PR adding yourself as a maintainer in the recipe here.

Thanks, I would like that yes. But I wonder if adding a user to the `maintainers` list of the recipe has any impact after the feedstock repository has been created. Perhaps @jakirkham or @ocefpaf know the answer?

**Comment by dopplershift** [comment]
The PR is the prescribed way to update maintainership. There's a script/service running somewhere that updates permissions after merging a PR. Part of the magic that @conda-forge/core has put together. 😁

**Comment by nicoddemus** [comment]
Wow that's cool. 😁

**Comment by jakirkham** [comment]
Correct, we run a cron job (currently a CI build on the web page repo) at least once daily (barring service outages and the like) that will transfer permissions to anyone recently added as a recipe maintainer. It also does other things like updates the feedstocks listing on the webpage and the [feedstocks repo]( https://github.com/conda-forge/feedstocks ). Long term we are planning to move this to an asynchronous webservice that updates after there is a push to the feedstocks.

**Pull request merged**
